### ISSUE TITLE
Version > 0.1.2 error on initialize

### ISSUE THREAD

**Issue by ghost** [zloeber/ModuleBuild#1]
Hi,
on `Initialize-ModuleBuild`, after all user inputs are inserted, the script throw the error: `plaster/ModuleBuild/scaffold/build/docs/readthedocs not exists`.
On version <=  0.1.2 the error not occours.

**Comment by zloeber** [comment]
Thanks for reporting that glaring issue. I've fixed it and pushed to the gallery and committed to master. Please update and let me know if any other issues crop up.

**Comment by ghost** [comment]
Hi @zloeber, a little late :)
Problem seems to be live. I think cause is `Source = 'scaffold\build\docs\ReadTheDocs\*'` in [this row](https://github.com/zloeber/ModuleBuild/blob/44fe93019a695d91825bb3aa364d418ab5403665/plaster/PlasterContent.ps1#L153).
