### ISSUE TITLE
Question about ModuleBuild-Extension: Invoke-Build less verbose

### ISSUE THREAD

**Issue by schittli** [zloeber/ModuleBuild#12]
Good evening Zachary

I tried to extend ModuleBuild, which is quite complex if one doesn't know the structure, the template sources, and the workflows. 

Therefore I'm working on different small extensions for ModuleBuild and if you're interested in any of it, then please let me know.

The 1st one is a small change:

### Invoke-Build
Invoke-Build it is very verbose and I already contributed a small extension to set custom footers. In my environment, I will remove the footers, so that I get less useless information: 
The footer only takes up space, makes it harder to read the log and only says that a task is finished.
This is implicitly clear when the next task starts :-)
If you're interested in my changes, then I'll create a Pull Request for it as soon as I have it.

**Comment by zloeber** [comment]
Sure, I'll take whatever you have and roll it in if it makes sense to do so. 

And you are right about the complexity of ModuleBuild itself. Unfortunately I've yet to find a good way to apply changes to it in an automated manner. If you like though i can answer any questions you may have to the best of my abilities and perhaps we can flesh out the contributing guide further from there.

**Comment by justin-p** [comment]
I'm closing this issue because it has been inactive for 2 years.
