### ISSUE TITLE
Question about ModuleBuild-Extension: easy Version increment for ModuleBuild

### ISSUE THREAD

**Issue by schittli** [zloeber/ModuleBuild#13]
Good evening Zachary

I'm already working with this small patch: 
To easily increment the Version number during a build, I created the following switches:
```
[switch]$IncrementVersionMajor,
[switch]$IncrementVersionMinor,
[switch]$IncrementVersionPatch,
[switch]$IncrementVersionBuild
```
So I don't need to know the exact new version number to set it to a new value,
I can simply add call e.g. `Build.ps1 -IncrementVersionPatch`

**Comment by justin-p** [comment]
Closing issue since there is a PR for this. https://github.com/zloeber/ModuleBuild/pull/16
