### ISSUE TITLE
Question about ModuleBuild-Extension: Plaster created Files with a reference to the used template

### ISSUE THREAD

**Issue by schittli** [zloeber/ModuleBuild#15]
Good evening Zachary

I guess that most contributors have a lot of work to find the right Template which was used to build files.

Therefore, I created a Plaster Pull-Request (I'm pretty sure it will pass the 2nd review) and it will offer the new Variable `PLASTER_TemplateFileSource`. 
This allows to add a reference to the used Template, so that Contributors can easily find the source they have to modify :-), for example:
```
# Built by Plaster, Version <%=$PLASTER_Version%>
# Used Template Root: <%=$PLASTER_TemplatePath%>
# Used Template File: <%=$('.' + $PLASTER_TemplateFileSource.Substring($PLASTER_TemplatePath.Length))%>
# Used Template File: <%=$PLASTER_TemplateFileSource%>
```
Results in (it's an example, I guess that the 2nd and 3rd Line would be enough, the 3rd Line is probably the most important):
```
# Built by Plaster, Version 1.1.0
# Used Template Root: C:\Program Files\WindowsPowerShell\Modules\ModuleBuild\0.2.2\plaster\ModuleBuild
# Used Template File: .\scaffold\Build.template
# Used Template File: C:\Program Files\WindowsPowerShell\Modules\ModuleBuild\0.2.2\plaster\ModuleBuild\scaffold\Build.template
```

At least for me, it will help a lot to touch the right files.

If you're interested in any extension, please let me know.
I will create individual Pull requests for each one (as soon as I have it :-)).

Kind regards,
Thomas

**Comment by justin-p** [comment]
Hi @schittli, right now we are (still) using a embedded/custom version of Plaster duo some [missing functionally not added to the main project that we need for ModuleBuild to work. ](https://github.com/PowerShell/Plaster/pull/254) As long we are bound to this specific modified version we sadly can't integrate upstream changes duo the maintenance overhead needed to do so. I also rather not change anything extra in the included plaster that is needed for ModuleBuild to work.
