### ISSUE TITLE
Builds just won't run

### ISSUE THREAD

**Issue by merddyin** [zloeber/ModuleBuild#18]
I'm relatively new to true DevOps as it relates to PowerShell, though I have been building modules for some time now. I've lately been trying to up my game though, which is how I came across your module. I used it to convert a few older projects to the framework, though I had not yet had opportunity to try a build until now, and it fails every time at the point of attempting to import the project module.

The ModuleFullPath is resolving correctly, but the build process throws the catch error (line 120) every single time. I have tested importing the module directly using the full path, and it imports with no issues. I currently only have a single private function. VSCode isn't finding any issues with any code, though there was originally a path issue with the default NLog plugin that I fixed (it's loaded into plugins\nlog\NLog\NLogModule and load.ps1 didn't have second NLog).

Any help is appreciated.

- OS:  Windows 10 1803 (Build 17134.286)
- PowerShell Version:  5.1
- List the steps to reproduce the problem below (if possible attach a screenshot and/or link to the code): Create new module project via Initialize-ModuleBuild -Path C:\Users\<myuser\Documents\Dev\Projects\<MyModule>
Add a single private function via Add-PublicFunction -name Get-MSBLocalUserRpt -templatename:PlainPublicFunction
Completed all function elements, updated manifest, added additional supporting module to Plugins folder, with an appropriate load and unload.ps1 using the nlog plugin as a template.
Configured both the buildenvironment.json and ps1 files
     Force true
     ForceInstallModule True
     AnalyzeCode False
     CodeHealthReport False
     CombineFiles True
     TranscriptEnabled True     
     Add tags
     PlatyPSVerbose True
     ReadTheDocs False

Run Build.ps1 -BuildModule

Task /./Configure/ValidateRequirements
* Validating System Requirements for Build
Done /./Configure/ValidateRequirements 00:00:00.0029921
Task /./Configure/PreBuildTasks
* Running any Pre-Build scripts
Done /./Configure/PreBuildTasks 00:00:00.0069822
Task /./Configure/LoadRequiredModules
* Loading all required modules for the build framework
  Importing PlatyPS Module
Done /./Configure/LoadRequiredModules 00:00:00.1389063
Task /./Configure/LoadModuleManifest
* Loading the existing module manifest for this module
Done /./Configure/LoadModuleManifest 00:00:00.0039891
Task /./Configure/LoadModule
* Attempting to load the project module.
ERROR: Unable to load the project module: C:\Users\<myuser\Documents\Dev\Projects\<mymodule>\<mymodule>.psm1
At C:\Users\<myuser>\Documents\Projects\Projects\<mymodule>\<mymodule>.build.ps1:120 char:9
+         throw "Unable to load the project module: $($ModuleFullPath)"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 7 tasks, 1 errors, 3 warnings 00:00:00.4831746
It then runs a bunch of cleanup tasks before finally showing:
Build succeeded with warnings. 2 tasks, 0 errors, 3 warnings 00:00:01.2732542

**Comment by justin-p** [comment]
Ran into the same issue.   
Changed the LoadModule task in the 'ModuleName'.build.ps1 to return a more detailed error message.

```Powershell
# Synopsis: Load the module project
task LoadModule {
    Write-Description White 'Attempting to load the project module.' -Accent

    $ModuleFullPath = Join-Path $BuildRoot "$($Script:BuildEnv.ModuleToBuild).psm1"
    try {
        $Script:Module = Import-Module $ModuleFullPath -Force -PassThru
    }
    catch {
        $PSCmdlet.ThrowTerminatingError($PSItem)
        #throw "Unable to load the project module: $($ModuleFullPath)"
    }
}
```
After doing so i was able to pinpoint it to a missing DLL for Nlog. 
```Powershell
Done /. 00:00:00.9688131
Build Failed with the following error:
C:\Users\User\Documents\WindowsPowerShell\Modules\InvokeBuild\5.4.2\Invoke-Build.ps1 : The specified module ''C:\SomePath\SomeModule\plugins\nlog\NLog\nlogmodule\lib\Nlog.dll'' was not loaded because no valid module file was found in any module directory. 
```
After manually creating the lib folder, placing the Nlog.dll there and fixing the path in 'Load.ps1' the issue seems fixed.   
~~Haven't looked at it yet but my guess is that `Initialize-ModuleBuild`/Plaster skips the NLog.dll ?~~
Issue is related to `PlasterContent.ps1`. Created a pull reqeust that contains a fix.

**Comment by justin-p** [comment]
This is fixed in the most recent build.
