### ISSUE TITLE
'Cannot process -File' almost at the end of Initialize-ModuleBuild execution

### ISSUE THREAD

**Issue by ghost** [zloeber/ModuleBuild#2]
Almost at the end of `Initialize-ModuleBuild` execution, after assets copying, PS throw an exception similar to:

> Cannot process -File ' D:\rep\some\foo '. The file has no extension 'ps1'. Specify a valid Windows PowerShell script file name and try again.

_(note this error description is translated from the Italian language, so it might be a little different in English)._

**Comment by zloeber** [comment]
Are you able to replicate this issue with the most recent release? What is the command you are running exactly if so?

**Comment by ghost** [comment]
Hi @zloeber if you take a look at [this PR](https://github.com/zloeber/ModuleBuild/pull/3) you can see the issue root ([commit reference](https://github.com/zloeber/ModuleBuild/pull/3/commits/5edf05dcc920770799737d57dbe20c595fd10331)). It is related to path containing **spaces**.
