### ISSUE TITLE
Missing CBH blocking build

### ISSUE THREAD

**Issue by PshMike** [zloeber/ModuleBuild#21]
- OS:  Windows 10 ( 2004 )
- PowerShell Version:  5.1.19582.1001
- List the steps to reproduce the problem below (if possible attach a screenshot and/or link to the code): 

Initialize-ModuleBuild used to create new module named myToolBox
Add-PublicFunction used to add simple function named New-HelloWorld

New-HelloWorld has CBH for required fields

When I use Invoke-Build to build the module I get a notification in the task "CreateHelp" about missing help content. See Invoke-Build-Log.txt in zip file along with simple project.

Updating the file listed does no good, it just gets reset when I run Invoke-Build again

[test004.zip](https://github.com/zloeber/ModuleBuild/files/4341589/test004.zip)

**Comment by justin-p** [comment]
Hi @mjenne,

Did you add Comment Based Help to your function ? If not you get these errors.
ModuleBuild includes a task that adds CBH for you. If you update to the most recent build (0.3.0 in the repo) `.\Build.ps1 -AddMissingCBH` should do the trick.
