### ISSUE TITLE
my build is not transferable to a clean system

### ISSUE THREAD

**Issue by sundmoon** [zloeber/ModuleBuild#4]
- OS:  **10.0.16299**
- PowerShell Version:  **5.1.16299.19**

I have a freshly generated and being built successfully build folder

https://www.upload.ee/files/7658179/3.7z.html
[3.zip](https://github.com/zloeber/ModuleBuild/files/1466696/3.zip)

when I try to build it on another clean system the build fails

Moreover, while it generates some red errors, the final verdict is different depending on the host
The powershell console says the build failed, but ISE says it was successful.

**Comment by zloeber** [comment]
I've downloaded your attachment and built it on my workstation without issues. I'll attempt to test this out again on a completely fresh workstation as well. Do you have any of the failure build output I can review?

**Comment by sundmoon** [comment]
I am apologize, the same output of both hosts

Done /./Configure/LoadRequiredModules 00:00:03.1047202
Task /./Configure/LoadModuleManifest
* Loading the existing module manifest for this module
Done /./Configure/LoadModuleManifest 00:00:00.1875121
Task /./Configure/LoadModule
* Attempting to load the project module.
At C:\3\Toolset.build.ps1:109 char:1
+ task LoadModule {
+ ~~~~~~~~~~~~~~~~~
At C:\3\Toolset.build.ps1:176 char:1
+ task Configure ValidateRequirements, PreBuildTasks, LoadRequiredModul ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\3\Toolset.build.ps1:874 char:1
+ task . Configure, CodeHealthReport, Clean, PrepareStage, GetPublicFun ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**Build FAILED.** 7 tasks, 1 errors, 0 warnings 00:00:07.6074434
Build Failed with the following error:
Unable to load the project module: C:\3\Toolset.psm1
At C:\3\Toolset.build.ps1:117 char:9
+         throw "Unable to load the project module: $($ModuleFullPath)"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to load ...\3\Toolset.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to load the project module: C:\3\Toolset.psm1


Attempting to clean up the session (loaded modules and such)...
Build BuildSessionCleanup C:\3\build\Toolset.buildenvironment.ps1
Task /BuildSessionCleanup
* Cleaning up the build session
  Removing modules
   Removing PlatyPS module (if loaded).
   Removing Pester module (if loaded).
   Removing PSScriptAnalyzer module (if loaded).
   Removing Powershell-YAML module (if loaded).
   Removing PSCodeHealth module (if loaded).
   Removing Toolset module  (if loaded).
  Runing post-build scripts
Done /BuildSessionCleanup 00:00:00.2522699
**Build succeeded.** 1 tasks, 0 errors, 0 warnings 00:00:00.5625125

**Comment by justin-p** [comment]
Hi @sundmoon, a lot of changes have been merged since 2017. Could try again with the most recent build included in the repo ? (PSGallery still needs updating)
If the issue still exists please (re)open a issue.
