### ISSUE TITLE
Files in build\cleanup are not executed

### ISSUE THREAD

**Issue by jhochwald** [zloeber/ModuleBuild#5]
- OS:  Windows 10 1709
- PowerShell Version:  5.1.16299.98 (Desktop)
- List the steps to reproduce the problem below (if possible attach a screenshot and/or link to the code): Generated a dummy file that create a new temp file. Tried Write-Warning and Write-Error as well

Files are located here: `\build\cleanup` wher your readme.md is located.

Nothing happens. And I wasn't even able to find any matching code that looks like an cleanup execution.

**Comment by jhochwald** [comment]
Think I found something:
In the generated build script (e.g. _mymodule.build.ps1_) I found the following lines:
`$CleanupPath = Join-Path $BuildToolPath 'shutdown'`

This should be `$CleanupPath = Join-Path $BuildToolPath 'cleanup'` or you have to change the directory name.
As soon as I put a create the directory `shutdown` all files in there are executed.

Example:
`  Runing post-build scripts
   Dot sourcing shutdown script file: shutdown1.ps1
WARNING: Here we go
C:\temp\mymodule
WARNING: Here we go, again`

The shutdown1.ps1 scripts should write the warnings... Just for my test :)

**Comment by zloeber** [comment]
They are now (as of build 0.2.2)! Thanks for reporting this bug.

Cheers,
Zach
