### ISSUE TITLE
Question: Shouldn't modulename.buildenvironment.template do anything with $RequiredModules?

### ISSUE THREAD

**Issue by schittli** [zloeber/ModuleBuild#7]
Good morning

**Thank you very much for this great Module!**, it's annoying that M$ does not provide such Tools out of the PowerShell box, while M$ is asking an outrageous amount of money for their products.

I try to understand your Module and I stumbled across the treatment of **`$RequiredModules`** at the very end of the template:

`ModuleBuild/plaster/ModuleBuild/scaffold/build/modulename.buildenvironment.template`

``` PowerShell
# If the variable is already defined then essentially do nothing.
# Otherwise we create a baseline variable first in case this is a first time run, then
# check for an exported .xml file with persistent settings for any run thereafter
if ((Get-Variable 'BuildEnv' -ErrorAction:SilentlyContinue) -eq $null) { 
…
    ########################################
    # !! Please leave anything below this line alone !!
    ########################################
    $PersistentBuildFile = join-path $PSScriptRoot "<%=$PLASTER_PARAM_ModuleName%>.buildenvironment.json" 
…
    $RequiredModules = @('PlatyPS', 'Pester')

    # Some optional modules
    if ($Script:BuildEnv.OptionAnalyzeCode) {
        $RequiredModules += 'PSScriptAnalyzer'
    }

    if ($Script:BuildEnv.OptionGenerateReadTheDocs) {
        $RequiredModules += 'Powershell-YAML'
    }

    if ($Script:BuildEnv.OptionCodeHealthReport) {
        $RequiredModules += 'PSCodeHealth'
    }
} 
```

it's strange that you set the Variable `$RequiredModules`, but then you're not doing anything with it. 
I would have expected that something like `Install-Module` gets called.

Did I miss something or is it a mistake?

Thanks a lot for your support!, 
kind regards, Thomas

**Comment by zloeber** [comment]
Hello,

Good point, I moved that particular code to its own invoke-build task (LoadRequiredModules) so I'll be certain to remove it from the next release.

**Comment by schittli** [comment]
Hello Zachary,
thank you for your explanation (and the cleanup :-)), 
the module is **much** more complex than I would have expected. 
Thanks a lot for your work.
Kind regards, Tom
