### ISSUE TITLE
Should this work?: .\Build.ps1 -test

### ISSUE THREAD

**Issue by schittli** [zloeber/ModuleBuild#8]
Hello Zachary
I'm very sorry, I have a 2nd question:
In `ModuleBuild/plaster/ModuleBuild/scaffold/readme.md` we can read:
```
This module is tested with the PowerShell testing framework Pester. 
To run all tests, just start the included test script `.\Build.ps1 -test` 
or invoke Pester directly with the `Invoke-Pester` cmdlet in the tests directory. (…)
```
Is my assumption correct that `.\Build.ps1 -test` still have to be implemented?
I ask because `.\Build.ps1` has no Parameter called `[switch]Test`

Thanks a lot, kind regards, Tom

**Comment by zloeber** [comment]
No apologies required. You are right, there really hasn't been a great deal of effort put into the unit testing portion of the framework. I started down that road and never fully implemented it. I had a hard time coming up with a good solid set of general PowerShell module unit tests to include with the project (that psscriptanalyzer didn't already cover in some manner). I'll put this in the project pipeline now though as it is long past due.

**Comment by justin-p** [comment]
`.\Build.ps1 -test` now works on the most recent build of ModuleBuild. By default it runs included meta tests with pester.
